SU-SWS/stanford_profile_helper

.gitignore
composer.json
src/Config/ConfigOverrides.php
stanford_profile_helper.module
stanford_profile_helper.services.yml
tests/src/Unit/Config/ConfigOverridesTest.php

- Supporting functions for https://github.com/SU-SWS/stanford_profile/pull/220
- Adds state to config page form and clear render cache on submit
- Tuesday July 28th
- Medium
1. Review code
2. See form at https://lockupsettings-dev.sites.stanford.edu/admin/config/system/lockup-settings for functionality
- Cardinalsites
- SOE
- SAA
- Earth Sites
- LelandD8
- D8CORE-1472 and others linked to it
- https://github.com/SU-SWS/stanford_profile/pull/220
- https://github.com/SU-SWS/stanford_basic/pull/170

D8CORE-1472: Config pages lockup Form helpers

---

stanford_profile_helper.module

- Before field storage save, remove the field permissions third party settings if we don't need it
- see https://github.com/SU-SWS/stanford_profile/pull/295
- :man_shrugging:
- low
1. checkout this branch and clear cache
1. create a new field on any entity
1. export the config
1. verify the exported config doesn't have the field permissions module as a dependency.

Added presave to remove all field permissions from field storage that arent needed

---

stanford_profile_helper.module

- Per Ishi's feedback, we needed a little more consistency between the media library embeddable forms and the wysiwyg embeddables form.  We do these changes in the stanford_profile_helper repo, since they are only for our profiles, and not needed in the stanford_media module itself.
- next code cutoff.
- 3 out of 10.
1. Install this version of the module.
2. Browse to /media/add/embeddable
3. Verify the oEmbed field is labeled 'oEmbed URL'
4. Verify there is a link to the SNOW form in the help text below the oEmbed field.
5. Try to add a new Embeddable through the WYSIWYG.  Confirm the labels and the SNOW form link match correctly.
- https://github.com/SU-SWS/stanford_profile/pull/299  <-- tests.
- [PR …

D8CORE-2644: Added additional help text and snow form links

---

stanford_profile_helper.module

- Fix the problem when taxonomy terms are moved around and needs to rebuild the menu.
- asap
- high
1. Add a new taxonomy item for people and nest it under "staff"
2. Refresh /people page and see no new taxonomy items
3. Edit the taxonomy for people and move the new taxonomy item to the top level 
4. Refresh /people page and see the new taxonomy item in the position you placed it in the taxonomy
5. Edit the taxonomy for people and move the new taxonomy item back under another item
6. Refresh the /people page and see the new taxonomy item is gone
Tests are in https://github.com/SU-SWS/stanford_profile/pull/305

D8CORE-2613: Delete taxonomy menu links when the parents change

---

stanford_profile_helper.module

- Limit taxonomy terms to 1 parent
- Added help text on taxonomy term form.
- 10/14
- low
1. checkout this branch and clear caches
1. go to create a new taxonomy term
1. verify you can only choose 1 parent.

D8CORE-2184 Adjust taxonomy terms to only 1 parent

---

stanford_profile_helper.module
tests/codeception/acceptance/ContentCest.php

- If the parent menu is external or absolute, not break when adding children links.
- 10/20
- medium
1. create a parent menu item (via node or just a regular menu item) with a full absolute url to anything
1. create another menu item with any url and choose to put it under the parent item you created earlier
1. verify when you save it doesn't blow up.

D8CORE-000 Fixed breaking if the parent menu item is external

---

stanford_profile_helper.module

- Don't allow the lists and entity reference paragraph types OOTB. We'll give access to a subset of sites at first to allow any unknown bugs to be discovered.
- https://github.com/SU-SWS/stanford_profile/pull/312
- 10/30
- medium
1. Checkout this branch
1. edit/create a basic page
1. see that you don't have the paragraph options for lists or content reference
1. `drush sset stanford_profile_allow_all_paragraphs 1`
1. edit/create a basic page
1. see that you now have the paragraph options for lists and content reference

D8CORE-2875: Limit paragraph choices for now

---

stanford_profile_helper.module

- Keep relations fieldset open on taxonomy term forms.
- 11/5
- low
1. checkout this branch.
1. edit/create a taxonomy term
1. verify the relations group is open.

D8CORE-2183 Keep the relations fieldset open by default on term form

---

stanford_profile_helper.module

- Removed title attribute that has special characters and is super long.
- 12/3
- medium
1. checkout this branch and clear caches
1. view the `/people` page
1. inspect the sidebar menu items
1. verify the links don't contain a `title` attribute.

D8CORE-2668 Removed title attribute from taxonomy menu items

---

stanford_profile_helper.module

- Remove the views from the publication view for the viewfield.
- 2/3
- high
2. `drush sset stanford_profile_allow_all_paragraphs 1`
2. create a basic page
3. add a list paragraph type
4. ensure you only get the "APA List" and "Chicago List" from the publications view options.

limit the publication views in the viewfield

---

stanford_profile_helper.module

- During config sync, theres a part where it creates a migration_group entity. When it does that, it doesn't set the UUIDs to match the config sync. This causes a circular issue because the config sync will try to delete and re-create it. each time with non-matching uuids. This PR sets the UUID to match the config sync file during save.
-  see https://gitlab.com/drupalspoons/migrate_plus/-/blob/8.x-5.x/migrate_plus.module#L56
- 2/4
- high
1. delete a config entity (field or node type or something)
2. recreate it with the same name
3. check to make sure the UUID still matches that from the config sync directory.

Set config entity uuids when they are created if they dont match

---

stanford_profile_helper.module

- use the custom `viewfield_block` so that we can have different blocks allowed in the viewfield fields.
- It doesn't change any underlying functionality, it just allows for 2 identical block categories.
- 3/3
- medium
1. Follow the steps in https://github.com/SU-SWS/stanford_profile/pull/370

D8CORE-3476 Create a new view display mode specific for viewfields

---

src/Config/ConfigOverrides.php
tests/src/Unit/Config/ConfigOverridesTest.php

- Override configs to allow site managers the ability to assign the custom roles that might be created on each site.
- 4/7
- medium
1. checkout this branch.
2. create a couple custom roles via the UI
3. masquerade as a site manager
4. verify you can assign the custom roles to a user of your choosing.

D8CORE-4021 Give site managers permission to assign custom roles

---

composer.json
src/Plugin/Block/PDBlock.php
src/Plugin/Derivative/ReactBlockDeriver.php
stanford_profile_helper.info.yml
stanford_profile_helper.module

- Enabled PDB module and provide a block for any PDB. This avoids the need for `pdb_react` or `pdb_angular` or other specific pdb submodules.
- I think we can ignore the code coverage diff test. Its a single line that is not "covered" by tests so I don't think there's any need for a test.
- :man_shrugging: 
- low
1. Nothing really to test. but see https://github.com/SU-SWS/stanford_profile/pull/432 for the inclusion to the product.

Added and enabled the PDB module

---

stanford_profile_helper.post_update.php

- Update hook to update media caption paragraphs with a link title.
- I did a query and there's at most 16 paragraphs to update per site. and that site is amptesting, so I don't believe batching the update is necessary.
- 7/8
- medium
1. Follow the steps in https://github.com/SU-SWS/stanford_profile/pull/423

D8CORE-4194 Set the link title value for media caption paragraphs

---

composer.json
src/Plugin/Filter/Mathjax.php
stanford_profile_helper.module
tests/src/Unit/Plugin/Filter/MathjaxTest.php

- Replace the mathjax text filter to remove the wrapping div that's not necessary and only add the external js when math formula is present
- Fixes wysiwyg media issues and spacing because of the additional wrapping div.
- 8/12
- medium
2. clear all caches
3. fill out a wysiwyg with some math formula like `$$x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$`
4. verify when you save the formula is still displayed

D8CORE-4690 Modify mathjax filter plugin to fix media and spacing issues

---

modules/stanford_intranet/stanford_intranet.module

- View the comments in the function for full information.
- I couldn't think of a way to test this via circleCI
- 8/12
- high
2. configure intranet `drush sset stanford_intranet 1`
3. clear caches.
4. Upload a jpg/jpeg file into the media library
5. embed that image in the wysiwyg and choose the `Circle` image style
6. verify the image is rendered when you save the page.

D8CORE-4696 Fix the access for private images that were converted to png files via styles

---

modules/stanford_intranet/stanford_intranet.module

- Allow "download" access to files on config pages (logo field)
- Sept 2nd
- high
2. `drush sset stanford_intranet 1; drush cr`
3. Add a logo to the config page at `/admin/config/system/lockup-settings` & save
4. Verify the logo displays for you on the home page
5. using masquerade or disabling saml, view the home page as a contributor or a user with no roles
6. verify the logo still displays for you.

D8CORE-4733 Allow file downloads for fields from config pages

---

stanford_profile_helper.module

- Under some circumstances, the `stanford_profile_helper` module was applying a constraint on the global message field before it was created during automated testing.  This was causing codeception tests to fail in `engineering_profile` since it was erroring out before installation was complete.  This PR corrects the problem by checking to make sure the field isn't NULL before attempting to apply the constraint.  No new functionality is introduced. 
- before next release
- 2, since it only affects tests and then not always.
- low
1. Take a look at the small change.
2. Verify tests pass.
- Is there a config:export in this PR that changes the config sync directory? No.

Added check to make sure field exists before adding constraint

---

js/stanford_profile_helper.mathjax.js
stanford_profile_helper.libraries.yml
stanford_profile_helper.module

- Configure mathjax so that formulas can't be placed in <p> tags.
- 9/30
- high
1. checkout this branch and clear caches
2. create a page and put this formula in the page title and in the body. `\(ax^2 + bx + c = 0\)`
3. after saving verify the formula in the page header is still raw text, but the one in the body was converted to the formula.

D8CORE-4793 Configure mathjax to only target equations in <p> tags

---

stanford_profile_helper.module

- related to https://github.com/SU-SWS/stanford_profile/pull/464
- Remove the Stanford Basic FA library if the FA module exists
- 11/19
- low
1. follow steps in https://github.com/SU-SWS/stanford_profile/pull/464
2. checkout this branch.
3. View any page
4. inspect the page and verify you only see 1 source coming from the font awesome library, not two different versions.
5. ie you should not see something like this: 

D8CORE-4246 unset stanford_basic FA library if the FA module exists

---

stanford_profile_helper.module

- Check if the form as VBO before sorting actions
- Fixes a warning on the `/admin/media` list page.
- 1/20/22
- low

Check if the form as VBO before sorting actions

---

stanford_profile_helper.module

- When importing a list of redirect, the destination might be `/about` but it is saved in that way in the database. It's saved like `internal:/about`. Ideally it would target the node itself if there is one. This will convert the alias to the internal path that targets the entity.
- 1/20
- medium
1. checkout this branch and clear caches
2. create a csv for redirects like:
```
From,To
/foo-bar,/research
```
3. Import the csv on `/admin/config/search/redirect/import`
4. edit the newly created redirect
5. validate it is tied to the node and not just the alias.

Modify the imported redirects to point at the node instead of the alias

---

stanford_profile_helper.module

- Purge the source url when a redirect is saved.
- Currently if a user visits a url that doesn't exists Varnish will cache the 404 response. This is good in 99.9% of scenarios. But when a user creates a redirect for the 404 page, varnish cache needs to be cleared so the redirect can take action.
- 1/29
- medium
1. Visit or curl a url on the prod or test environment that will generate a 404 reponse. Curl is the fastest. `curl -I https://amptesting-test.sites.stanford.edu/[enter-some-url]`. Do this twice for the same url (to establish the age)
2. verify the response code is 404 and the age is > 0
3. log into the site and create a redirect for that url you used.
4. curl again, and verify the age > 0 and the response code is 404.
5. Follow the same steps on the dev environment with this …

Purge the source url when a redirect is saved

---

stanford_profile_helper.module

- Move the schedule publisher field into the "publish information" group
- Added help text to the scheduler field.
- Adjust the increment of the schedule field to 4 hours, but allow custom site override
- Disable the "Publish" checkbox if the schedule publish field is filled.
- 3/16
- medium
2. clear caches
3. verify the 3 above when creating/editing a piece of content.

D8CORE-5574 D8CORE-5575 D8CORE-5576 Adjustments to the schedule module form displays

---

stanford_profile_helper.install

- Update hook to enable the minimally branded theme. Avoids the need for devs to enable it via drush.
- 3/17
- high
1. follow steps in https://github.com/SU-SWS/stanford_profile/pull/508

Enable minimally branded theme for easier switching

---

composer.json
modules/stanford_intranet/drush.services.yml
modules/stanford_intranet/src/Commands/IntranetCommands.php
modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php

- Drush command to enable intranet and do all the config pages work for us from CLI.
- Unfortunately it needs to be deployed to the server to use, so we can't use it until after the next release.
- :shrug: 
- low
1. checkout this branch.
2. clear caches
3. run `drush stanford-intranet:setup --help`
4. view the options and the way to use the command.
5. run the command
6. verify any options you configured get applied and visible on the `/admin/config/people/simplesaml` config page.

Drush command to easily set up intranets

---

modules/stanford_intranet/drush.services.yml
modules/stanford_intranet/src/Commands/IntranetCommands.php
modules/stanford_intranet/src/StanfordIntranetManager.php
modules/stanford_intranet/src/StanfordIntranetManagerInterface.php
modules/stanford_intranet/stanford_intranet.install
modules/stanford_intranet/stanford_intranet.services.yml
modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
modules/stanford_intranet/tests/src/Kernel/StanfordIntranetManagerTest.php

- Update hook and drush commands to move all public files into private directories.
- asap
- high
2. enable intranet `drush sset stanford_intranet 1`
3. run database updates `drush updb` or `drush stanford-intranet:move-files` to run just the file movements
4. view any media and validate the file/image exists in the private directory.

Update hook and drush command to move all public files into private file system.

---

modules/stanford_intranet/lib/scss/base/intranet.scss

- Getting rid of the white bar that appears between the page-content and footer at some screen sizes.
- When convenient
- High
- High
2. Navigate to an intranet site (e.g. https://cabinet.stanford.edu/roster) and confirm the white bar between the page-content and local footer is no longer appearing.
- https://stanfordwebservices.slack.com/archives/C02D5MQUS3A/p1683752914604879

Fixup white bar above footer
