SU-SWS/stanford_profile_helper

- .github/workflows/tag_commits_to_master.yml
- README.md
- stanford_profile_helper.module
- Fixed the "All Media" toolbar link
- Changed the "master" reference to "main"
- 7/8
- medium
1. Checkout this branch
1. clear caches
1. see the menu link the admin toolbar "All Media"
> D8CORE-2282 Fix the admin toolbar menu link text

- CHANGELOG.md
- composer.json
- stanford_profile_helper.info.yml
- initial release
- 7/13/2020
- it's necessary to have a release here to build the profiles.
> Initial release

- stanford_profile_helper.module
- https://www.drupal.org/project/views_bulk_operations/issues/3055770#comment-13116724
- remove that checkbox to prevent unwanted action.
- 7/29
- medium
1. checkout this branch.
1. view `/admin/content`
1. validate the checkbox to select all items in the view doesn't exist.
> CSD-258 Hide checkbox that could cause damage

- modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
- modules/stanford_profile_styles/stanford_profile_styles.module
- stanford_profile_helper.module
- Changes to reflect changes in the profile.
- Sept 4th
- High
1. Do a full build of D8CORE-1609 of cardinalsites
2. Run through the config for global messages and the super footer
3. Ensure the css styles are still attached
- D8CORE
- SOE
- D8CORE-2490
- D8CORE-2376
> D8CORE-2490: Name key changes.

- stanford_profile_helper.module
- Adds field based permissions to embeddable form open embed code field
- Monday Morning.
- High
1. Check out the code in https://github.com/SU-SWS/stanford_media/pull/64
2. Check out this code
3. Run tests in https://github.com/SU-SWS/stanford_profile/pull/273 
or
3. Validate with different users that can or cannot access the field.
> D8CORE-2521: Add hook for field permission on open embed field.

- stanford_profile_helper.module
- Fixed the form submitted values to be an array like the entity is expecting it to be.
- asap
- high
1. edit/create any taxonomy term
1. validate no php errors occur.
> D8CORE-2184 Add element validate to tweak the submitted value

- stanford_profile_helper.module
- Limit view options in the react widget.
see https://github.com/SU-SWS/stanford_profile/pull/310
> D8CORE-2856 Remove unwanted views from the list paragraph type

- stanford_profile_helper.post_update.php
- Update hook for https://github.com/SU-SWS/stanford_profile/pull/324
- same time as https://github.com/SU-SWS/stanford_profile/pull/324
> D8CORE-2570 Update hook to create the intro blocks

- .github/workflows/tag_commits_to_master.yml
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> Change the github actions to tag PRs on master

- modules/stanford_profile_styles/stanford_profile_styles.module
- fixed the path to the ckeditor style sheet.
- 
- 
> Fixed ckeditor styles path

- stanford_profile_helper.module
- Don't allow list paragraph types to choose unwanted views.
- 3/3
- medium
1. see https://github.com/SU-SWS/stanford_profile/pull/368
2. verify the list paragraph type does not allow you to choose Events -> Schedule or the Publications -> Publication type view displays.
> D8CORE-3564 Dont allow the new pub type view in the view paragraph type

- composer.json
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> update admin toolbar

- stanford_profile_helper.module
- Prevent unpublishing the home, 404, and 403 pages.
- tests in https://github.com/SU-SWS/stanford_profile/pull/392
- 4/7
- medium
2. go to edit the home page, 404 , or 403 pages
3. verify you don't have the "Published" checkbox at the bottom
> D8CORE-2853 Prevent unpublishing home, 403, or 404 pages

- src/Plugin/Validation/Constraint/GlobalMessageConstraintValidator.php
- tests/src/Unit/Plugin/Validation/Constraint/GlobalMessageConstraintValidatorTest.php
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> D8CORE-2766 Tests

- stanford_profile_helper.module
- remove the "Unlock" button on the node form.
- asap
- high
2. edit an existing node
3. verify the "Unlock" button at the bottom doesn't exist.
> D8CORE-4115 Remove the "Unlock" button on node form

- modules/stanford_profile_styles/js/colorbox.js
- modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
- modules/stanford_profile_styles/stanford_profile_styles.module
- Use some javascript to tweak colorbox
- 5/18
- medium
1. checkout this branch and the branch in https://github.com/SU-SWS/stanford_profile/pull/415
2. clear caches & `drush cim -y`
3. Review the accessibility of the colorbox on an image gallery.
> D8CORE-4104 Improve colorbox with javascript

- stanford_profile_helper.post_update.php
- Update hook to add role to users who have custom Layout Builder content
- 9/30
- medium
1. follow steps in https://github.com/SU-SWS/stanford_profile/pull/451
> Update hook to add role for users with custom LB content

- js/stanford_profile_helper.siteimprove.analytics.js
- stanford_profile_helper.libraries.yml
- stanford_profile_helper.module
- Add site improve analytics script for prod sites when anonymous.
-10/7
- low
1. Locally, you won't be able to load the js unless you comment out some lines. So just review the JS and the hook logic.
> D8CORE-4679 Add site improve analytics js

- composer.json
- stanford_profile_helper.module
- Tests were failing in this: https://github.com/SU-SWS/stanford_profile/pull/462
- Tracing back the error, I found a problem in this module with the `stanford_profile_helper_form_media_embeddable_add_form_alter` function
- Here's the actual error: 
- This error was only occurring with the `contributor` role.
- This PR corrects that error, allowing tests to pass.
- asap
- Tests for the `stanford_profile` repo will likely fail until this is merged.
- Normal
1.  The failing tests are in the profile, not in this module, so you'll want to verify that the `MediaPermissionsCest: Test contributor perms` test in the `stanford_profile` module are passing.  The easy way is to verify passing tests on this PR: https://github.com/SU-SWS/stanford_profile/pull/462
- Is there a config:export in this PR …
> D8 core 4878

- stanford_profile_helper.module
- Convert the url object into a string.
- 11/19
- high
> Convert url object into a string for better rendering

- .circleci/config.yml
- modules/stanford_intranet/tests/src/Kernel/Plugin/Field/FieldWidget/EntityAccessFieldWidgetTest.php
- tests/src/Kernel/Plugin/Field/FieldWidget/SamlRoleMappingWidgetTest.php
> updated tests for D9.3

- stanford_profile_helper.module
- Remove local tabs from scheduler until a new release is made.
- See https://www.drupal.org/project/scheduler/issues/3224340
- 2/30
- medium
1. follow steps in https://github.com/SU-SWS/stanford_profile/pull/486
> D8CORE-5278 Removed unwanted menu links from scheduler

- modules/stanford_intranet/README.md
- modules/stanford_intranet/stanford_intranet.install
- modules/stanford_intranet/stanford_intranet.module
- Added `stanford_intranet.allow_file_uploads` state and functionality
- Tests are being written separately into https://github.com/SU-SWS/trustee_profile/blob/0fed57f2ba8fcf99988f2ab44f2fe245ab4dc27e/tests/codeception/acceptance/Users/IntranetCest.php#L139-L147
- ASAP
6-7
High-ish
1. Pull and setup locally
2. Try to add a file at `media/add/file` (should see Access Denied)
3. Enable `allow_file_uploads` state: 
* `drush sset stanford_intranet.allow_file_uploads 1`
* `drush @<site_alias> cr`
4. Reload and try to add a file at `media/add/file` (should be able to upload a file now)
5. Disable `allow_file_uploads` state: 
* `drush sset stanford_intranet.allow_file_uploads 0`
* `drush @<site_alias> cr`
6. Reload and try to add a file at `media/add/file` (should see Access Denied)
7. Review …
> BOT-8: Add intranet state to allow file uploads

- stanford_profile_helper.module
- Process the local footer pattern to add containers and classes for the 2nd and 3rd content block.
- 3/5
- medium
1. Follow the steps in https://github.com/SU-SWS/stanford_profile/pull/491
> D8CORE-4974 Process the local footer to wrap the second and thrid local footer contents

- stanford_profile_helper.post_update.php
- Update hook for path auto changes https://github.com/SU-SWS/stanford_profile/pull/505
- 3/15
- medium
1. follow steps in https://github.com/SU-SWS/stanford_profile/pull/505
> D8CORE-3345 Update hook to update paths for terms and content.

- stanford_profile_helper.module
- Adjusted scheduler help text
- Thursday
- high
2. view any node form
3. verify the help text on the scheduler field is updated.
> D8CORE-5686 Adjusted scheduler help text

- stanford_profile_helper.module
- stanford_profile_helper.services.yml
- The DS module provides a "limit" option on fields, but it doesn't work with all field formatters. Adjust the list field formatters to provide limit functionality.
- asap
- high
1. see https://github.com/SU-SWS/stanford_profile/pull/532
> D8CORE-5750 Modify field render arrays to better suite the DS module limits

- stanford_profile_helper.post_update.php
- Fixes fatal error on post update. This change allowed me to run the update without a fatal error.
- See comment: https://github.com/SU-SWS/stanford_profile_helper/pull/183#issuecomment-1122834084
4. Verify...
- Other PRs
- Any other contextual information that might be …
> Added conditional to fix null fatal error on 8102 update.

- modules/stanford_courses/stanford_courses.install
- Adds update hook to correct migration table.
- Today
1. Test per: https://github.com/SU-SWS/stanford_profile/pull/638
- Other PRs
- [AMP …
> D8CORE-6237: Added install file and migration to correct the courses table

- modules/stanford_courses/templates/components/course-list/course-item-list.twig
- modules/stanford_courses/templates/components/course-vertical-teaser/course-vertical-teaser.twig
- I removed the small bit of Twig which was stripping the spaces between the course subject and course code in the two template which are used for the course display.
- 🤷‍♂️ 
- low
- low
2. Import some courses.
3. Navigate to `/courses`
4. Verify there is now a space between the course subject and course code in the listing.
5. Verify the same is true of the Card display in a list.
- Is there a config:export in this PR that changes the config sync directory? NO
- Other PRs
- [AMP …
> D8CORE-5865: Prevented spaces from being stripped from course code

- src/Config/ConfigOverrides.php
- stanford_profile_helper.post_update.php
> Override page_cache_query_ignore settings with view queries

- src/Config/ConfigOverrides.php
- stanford_profile_helper.module
> Refactored page_cache_query_ignore config override

- modules/stanford_policy/src/Entity/SuPolicyLog.php
- modules/stanford_policy/src/Form/SuPolicyLogSettingsForm.php
- modules/stanford_policy/src/SuPolicyLogAccessControlHandler.php
- modules/stanford_policy/src/SuPolicyLogInterface.php
- modules/stanford_policy/stanford_policy.install
- modules/stanford_policy/stanford_policy.links.menu.yml
- modules/stanford_policy/stanford_policy.links.task.yml
- modules/stanford_policy/stanford_policy.permissions.yml
- modules/stanford_policy/stanford_policy.routing.yml
- src/EventSubscriber/EntityEventSubscriber.php
> Replace ECK log entity with custom entity type

- src/EventSubscriber/EntityEventSubscriber.php
> Fixed the menu link content presave for the menu_link field module

- src/EventSubscriber/FormEventSubscriber.php
> Alter taxonomy form to provide a argument helper

- composer.json
- modules/stanford_layout_paragraphs/stanford_layout_paragraphs.module
- modules/stanford_profile_styles/stanford_profile_styles.module
- src/Plugin/Filter/SuCleanHtml.php
- stanford_profile_helper.libraries.yml
- stanford_profile_helper.module
- tests/src/Unit/Plugin/Filter/SuCleanHtmlTest.php
> Copy work from SUL over for decoupled tools

- modules/stanford_intranet/src/EventSubscriber/IntranetRouteSubscriber.php
- modules/stanford_intranet/stanford_intranet.services.yml
> Remove access to sitemap.xml for intranet sites

- modules/stanford_layout_paragraphs/src/EventSubscriber/StanfordLayoutParagraphsSubscriber.php
- modules/stanford_layout_paragraphs/stanford_layout_paragraphs.services.yml
- Instead of restricting the banner paragraph to a specific 1 column layout, make it based on the number of regions.
ASAP
- Med/High
3. Add a page with a `layout_paragraphs` components section. Add a one column section and a two column section.
4. Verify you can only add the Banner paragraph to the one column section and not the two column.
- Is there a config:export in this PR that changes the config sync directory? No
- Other PRs
- Anyone who should be notified? (`@mention` them …
> SDSS-763: Check for number of regions on banner restriction.
